In [3]:
import pandas as pd
import os

In [23]:
booking = pd.read_csv("data/raw/booking_log.csv")
participant = pd.read_csv("data/raw/participant_log.csv")

In [26]:
booking.isnull().sum()

event_timestamp         92
order_id                 0
booking_status           0
customer_id              0
driver_id           194035
trip_distance            0
pickup_latitude          0
pickup_longitude         0
dtype: int64

In [27]:
participant.isnull().sum()

event_timestamp        0
driver_id              0
participant_status     0
order_id               0
experiment_key         0
driver_latitude        0
driver_longitude       0
driver_gps_accuracy    0
dtype: int64

In [20]:
booking.shape[0]

699212

In [21]:
booking_unique = booking.drop_duplicates()
booking_unique.shape[0]

698233

In [ ]:
booking_unique[booking_unique.duplicated(subset="order_id")]

,event_timestamp,order_id,booking_status,customer_id,driver_id,trip_distance,pickup_latitude,pickup_longitude
1,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.000,-2.998461,104.788077
2,2015-05-12 05:55:10.496544 UTC,102254181112,COMPLETED,715281995014,2.211727e+11,2.000,-2.998461,104.788077
4,2015-05-12 05:29:38.214 UTC,105520285203,DRIVER_FOUND,957980952237,5.276724e+11,2.000,-2.970621,104.756226
5,2015-05-12 05:31:00.12 UTC,105520285203,CUSTOMER_CANCELLED,957980952237,5.276724e+11,2.000,-2.970621,104.756226
7,2015-05-18 04:32:57.633 UTC,113947347802,PICKED_UP,352787792790,4.766568e+11,2.000,-2.981196,104.718829
...,...,...,...,...,...,...,...,...
699206,2015-05-18 10:21:19.811 UTC,995905396208,DRIVER_FOUND,366602285072,6.149728e+11,9.916,-2.986197,104.761670
699207,2015-05-18 10:22:01.464 UTC,995905396208,CUSTOMER_CANCELLED,366602285072,6.149728e+11,9.916,-2.986197,104.761670
699209,2015-05-18 15:04:33.707 UTC,997608900030,DRIVER_FOUND,587801587010,4.395662e+11,9.916,-2.979303,104.745228
699210,2015-05-18 15:10:44.295 UTC,997608900030,PICKED_UP,587801587010,4.395662e+11,9.916,-2.979303,104.745228
699211,2015-05-18 15:32:07.381 UTC,997608900030,COMPLETED,587801587010,4.395662e+11,9.916,-2.979303,104.745228

In [13]:
dup_data = booking[booking.duplicated(keep=False)]
dup_data.head()

,event_timestamp,order_id,booking_status,customer_id,driver_id,trip_distance,pickup_latitude,pickup_longitude
192,2015-05-18 15:01:16.156 UTC,415252215301,CREATED,577794884928,NaN,2.125,-2.933223,104.788163
193,2015-05-18 15:01:16.156 UTC,415252215301,CREATED,577794884928,NaN,2.125,-2.933223,104.788163
195,2015-05-18 15:01:17.165 UTC,415252215301,DRIVER_FOUND,577794884928,8.320652e+11,2.125,-2.933223,104.788163
196,2015-05-18 15:01:17.165 UTC,415252215301,DRIVER_FOUND,577794884928,8.320652e+11,2.125,-2.933223,104.788163
3069,2015-05-18 13:46:16.567 UTC,471089963917,CREATED,364263398252,NaN,0.750,-3.003400,104.807224

In [11]:
dup_data.shape[0]

1766

In [15]:
unique_columns = [
        "order_id",
        "trip_distance",
        "pickup_latitude",
        "pickup_longitude",
    ]

dup_data = booking[booking.duplicated(subset=unique_columns)]

In [16]:
dup_data

,event_timestamp,order_id,booking_status,customer_id,driver_id,trip_distance,pickup_latitude,pickup_longitude
1,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.000,-2.998461,104.788077
2,2015-05-12 05:55:10.496544 UTC,102254181112,COMPLETED,715281995014,2.211727e+11,2.000,-2.998461,104.788077
4,2015-05-12 05:29:38.214 UTC,105520285203,DRIVER_FOUND,957980952237,5.276724e+11,2.000,-2.970621,104.756226
5,2015-05-12 05:31:00.12 UTC,105520285203,CUSTOMER_CANCELLED,957980952237,5.276724e+11,2.000,-2.970621,104.756226
7,2015-05-18 04:32:57.633 UTC,113947347802,PICKED_UP,352787792790,4.766568e+11,2.000,-2.981196,104.718829
...,...,...,...,...,...,...,...,...
699206,2015-05-18 10:21:19.811 UTC,995905396208,DRIVER_FOUND,366602285072,6.149728e+11,9.916,-2.986197,104.761670
699207,2015-05-18 10:22:01.464 UTC,995905396208,CUSTOMER_CANCELLED,366602285072,6.149728e+11,9.916,-2.986197,104.761670
699209,2015-05-18 15:04:33.707 UTC,997608900030,DRIVER_FOUND,587801587010,4.395662e+11,9.916,-2.979303,104.745228
699210,2015-05-18 15:10:44.295 UTC,997608900030,PICKED_UP,587801587010,4.395662e+11,9.916,-2.979303,104.745228
699211,2015-05-18 15:32:07.381 UTC,997608900030,COMPLETED,587801587010,4.395662e+11,9.916,-2.979303,104.745228

In [3]:
merged_data = pd.read_csv("data/processed/dataset.csv")

In [31]:
merged_data[merged_data.duplicated(keep=False)]

Empty DataFrame
Columns: [event_timestamp_x, driver_id_x, participant_status, order_id, experiment_key, driver_latitude, driver_longitude, driver_gps_accuracy, event_timestamp_y, booking_status, customer_id, driver_id_y, trip_distance, pickup_latitude, pickup_longitude, is_completed]
Index: []

In [32]:
merged_data.head()

,event_timestamp_x,driver_id_x,participant_status,order_id,experiment_key,driver_latitude,driver_longitude,driver_gps_accuracy,event_timestamp_y,booking_status,customer_id,driver_id_y,trip_distance,pickup_latitude,pickup_longitude,is_completed
0,2015-05-18 11:45:19.519 UTC,110283102582,CREATED,938125906616,309579604593,-2.981389,104.761898,2.0,2015-05-18 11:45:03.958 UTC,CREATED,786955815516,NaN,5.601,-2.980337,104.7612,0
1,2015-05-18 11:45:19.519 UTC,110283102582,CREATED,938125906616,309579604593,-2.981389,104.761898,2.0,2015-05-18 11:45:30.076 UTC,DRIVER_FOUND,786955815516,1.102831e+11,5.601,-2.980337,104.7612,0
2,2015-05-18 11:45:19.519 UTC,110283102582,CREATED,938125906616,309579604593,-2.981389,104.761898,2.0,2015-05-18 11:52:13.997 UTC,CUSTOMER_CANCELLED,786955815516,1.102831e+11,5.601,-2.980337,104.7612,0
3,2015-05-18 11:45:29.8 UTC,110283102582,ACCEPTED,938125906616,309579604593,-2.981389,104.761898,2.0,2015-05-18 11:45:03.958 UTC,CREATED,786955815516,NaN,5.601,-2.980337,104.7612,1
4,2015-05-18 11:45:29.8 UTC,110283102582,ACCEPTED,938125906616,309579604593,-2.981389,104.761898,2.0,2015-05-18 11:45:30.076 UTC,DRIVER_FOUND,786955815516,1.102831e+11,5.601,-2.980337,104.7612,1

In [38]:
merged_data.columns

Index(['event_timestamp_x', 'driver_id_x', 'participant_status', 'order_id',
       'experiment_key', 'driver_latitude', 'driver_longitude',
       'driver_gps_accuracy', 'event_timestamp_y', 'booking_status',
       'customer_id', 'driver_id_y', 'trip_distance', 'pickup_latitude',
       'pickup_longitude', 'is_completed'],
      dtype='object')

In [39]:
merged_data[['event_timestamp_x','event_timestamp_y','driver_id_x','driver_id_y']].head()

,event_timestamp_x,event_timestamp_y,driver_id_x,driver_id_y
0,2015-05-18 11:45:19.519 UTC,2015-05-18 11:45:03.958 UTC,110283102582,NaN
1,2015-05-18 11:45:19.519 UTC,2015-05-18 11:45:30.076 UTC,110283102582,1.102831e+11
2,2015-05-18 11:45:19.519 UTC,2015-05-18 11:52:13.997 UTC,110283102582,1.102831e+11
3,2015-05-18 11:45:29.8 UTC,2015-05-18 11:45:03.958 UTC,110283102582,NaN
4,2015-05-18 11:45:29.8 UTC,2015-05-18 11:45:30.076 UTC,110283102582,1.102831e+11

In [4]:
merged_data_v2 = pd.read_csv("data/processed/dataset.csv")

In [5]:
merged_data_v2.columns

Index(['event_timestamp_booking', 'order_id', 'booking_status', 'customer_id',
       'driver_id_booking', 'trip_distance', 'pickup_latitude',
       'pickup_longitude', 'event_timestamp_participant',
       'driver_id_participant', 'participant_status', 'experiment_key',
       'driver_latitude', 'driver_longitude', 'driver_gps_accuracy',
       'is_completed'],
      dtype='object')

In [10]:
merged_data_v2.head()

,event_timestamp_booking,order_id,booking_status,customer_id,driver_id_booking,trip_distance,pickup_latitude,pickup_longitude,driver_id_participant,participant_status,experiment_key,driver_latitude,driver_longitude,driver_gps_accuracy,is_completed
0,2015-05-12 05:25:23.904 UTC,102254181112,CREATED,715281995014,NaN,2.0,-2.998461,104.788077,221172732473,CREATED,697155500625,-2.998517,104.780779,123.623,0
1,2015-05-12 05:25:23.904 UTC,102254181112,CREATED,715281995014,NaN,2.0,-2.998461,104.788077,221172732473,ACCEPTED,697155500625,-2.998517,104.780779,123.623,1
2,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.0,-2.998461,104.788077,221172732473,CREATED,697155500625,-2.998517,104.780779,123.623,0
3,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.0,-2.998461,104.788077,221172732473,ACCEPTED,697155500625,-2.998517,104.780779,123.623,1
4,2015-05-12 05:55:10.496544 UTC,102254181112,COMPLETED,715281995014,2.211727e+11,2.0,-2.998461,104.788077,221172732473,CREATED,697155500625,-2.998517,104.780779,123.623,0

In [30]:
merged_data_v2.drop(columns='event_timestamp_participant', inplace=True)

In [48]:
booking_unique[booking_unique['booking_status']=='COMPLETED'].groupby('driver_id').size().reset_index(name='compl_count')

          driver_id  compl_count
0      1.000498e+11            1
1      1.000855e+11            6
2      1.002613e+11            1
3      1.003115e+11            2
4      1.003707e+11           31
...             ...          ...
13416  9.994564e+11           10
13417  9.996425e+11           14
13418  9.998398e+11            3
13419  9.998547e+11            2
13420  9.999924e+11            4

[13421 rows x 2 columns]

Read files after removing duplicates

In [14]:
booking = pd.read_csv("data/processed/booking_log.csv")
participant = pd.read_csv("data/processed/participant_log.csv")

In [15]:
print(participant.columns)
print(booking.columns)

Index(['event_timestamp', 'driver_id', 'participant_status', 'order_id',
       'experiment_key', 'driver_latitude', 'driver_longitude',
       'driver_gps_accuracy'],
      dtype='object')
Index(['event_timestamp', 'order_id', 'booking_status', 'customer_id',
       'driver_id', 'trip_distance', 'pickup_latitude', 'pickup_longitude'],
      dtype='object')

In [25]:
participant.head(2)

,event_timestamp,driver_id,participant_status,order_id,experiment_key,driver_latitude,driver_longitude,driver_gps_accuracy
0,2015-05-18 11:45:19.519 UTC,110283102582,CREATED,938125906616,309579604593,-2.981389,104.761898,2.0
1,2015-05-18 11:45:29.8 UTC,110283102582,ACCEPTED,938125906616,309579604593,-2.981389,104.761898,2.0

In [23]:
booking_participant = pd.merge(booking, participant, on = ['order_id','driver_id'], how = 'inner')

In [24]:
booking_participant.head()

,event_timestamp_x,order_id,booking_status,customer_id,driver_id,trip_distance,pickup_latitude,pickup_longitude,event_timestamp_y,participant_status,experiment_key,driver_latitude,driver_longitude,driver_gps_accuracy
0,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.0,-2.998461,104.788077,2015-05-12 05:25:24.056 UTC,CREATED,697155500625,-2.998517,104.780779,123.623
1,2015-05-12 05:25:24.67 UTC,102254181112,DRIVER_FOUND,715281995014,2.211727e+11,2.0,-2.998461,104.788077,2015-05-12 05:25:24.548 UTC,ACCEPTED,697155500625,-2.998517,104.780779,123.623
2,2015-05-12 05:55:10.496544 UTC,102254181112,COMPLETED,715281995014,2.211727e+11,2.0,-2.998461,104.788077,2015-05-12 05:25:24.056 UTC,CREATED,697155500625,-2.998517,104.780779,123.623
3,2015-05-12 05:55:10.496544 UTC,102254181112,COMPLETED,715281995014,2.211727e+11,2.0,-2.998461,104.788077,2015-05-12 05:25:24.548 UTC,ACCEPTED,697155500625,-2.998517,104.780779,123.623
4,2015-05-12 05:29:38.214 UTC,105520285203,DRIVER_FOUND,957980952237,5.276724e+11,2.0,-2.970621,104.756226,2015-05-12 05:29:38.123 UTC,ACCEPTED,243283239235,-2.970765,104.750961,13.425

In [14]:
complete_count = booking[booking['booking_status']=='COMPLETED'].groupby('driver_id').size().reset_index(name='compl_count')

In [15]:
complete_count.head()

      driver_id  compl_count
0  1.000498e+11            1
1  1.000855e+11            6
2  1.002613e+11            1
3  1.003115e+11            2
4  1.003707e+11           31

In [18]:
compl_count = pd.merge(complete_count, merged_data_v2, left_on="driver_id", right_on = "driver_id_booking", how="inner").drop(columns='driver_id')

In [27]:
compl_count[compl_count['booking_status']=='COMPLETED'].groupby('driver_id_booking').size().reset_index(name='compl_count')

       driver_id_booking  compl_count
0           1.000498e+11            2
1           1.000855e+11           16
2           1.002613e+11            2
3           1.003115e+11            4
4           1.003707e+11           66
...                  ...          ...
13416       9.994564e+11           20
13417       9.996425e+11           30
13418       9.998398e+11            6
13419       9.998547e+11            6
13420       9.999924e+11           16

[13421 rows x 2 columns]

In [11]:
booking.shape[0]

698233

In [12]:
participant.shape[0]

400104

In [13]:
merged_data_v2.shape[0]

1510833

In [3]:
transf_df = pd.read_csv("data/processed/transformed_dataset.csv")

In [4]:
transf_df.head(2)

,compl_count,order_id,booking_status,customer_id,trip_distance,driver_id_participant,participant_status,experiment_key,driver_gps_accuracy,is_completed,driver_distance,event_hour
0,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,ACCEPTED,786415716306,68.4,1,0.097266,3
1,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,CREATED,786415716306,68.4,0,0.097266,3

Feature Selection

In [18]:
transf_df_v2 = transf_df.drop(columns=['event_timestamp_booking','pickup_latitude','pickup_longitude','driver_latitude','driver_longitude','driver_id_booking'])

In [19]:
transf_df_v2.head(2)

,compl_count,order_id,booking_status,customer_id,trip_distance,driver_id_participant,participant_status,experiment_key,driver_gps_accuracy,is_completed,driver_distance,event_hour
0,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,ACCEPTED,786415716306,68.4,1,0.097266,3
1,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,CREATED,786415716306,68.4,0,0.097266,3

In [ ]:
#driver related columns - id, driver lat and long
#test train data different

In [ ]:
#why are there two driver IDs

In [29]:
#training data

transf_df = pd.read_csv("data/processed/transformed_dataset.csv")
transf_df.head(2)

,compl_count,order_id,booking_status,customer_id,trip_distance,driver_id_participant,participant_status,experiment_key,driver_gps_accuracy,is_completed,driver_distance,event_hour
0,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,ACCEPTED,786415716306,68.4,1,0.097266,3
1,1,865687867130,PICKED_UP,834237894830,1.37,100049799902,CREATED,786415716306,68.4,0,0.097266,3

In [17]:
#encode booking status, drop exp key, id cols 
transf_df.drop(columns=['customer_id','experiment_key'],inplace=True)

In [8]:
transf_df_v2['booking_status'].unique()

array(['PICKED_UP', 'DRIVER_FOUND', 'COMPLETED', 'DRIVER_CANCELLED',
       'CUSTOMER_CANCELLED'], dtype=object)

In [9]:
transf_df_v2['participant_status'].unique()

array(['ACCEPTED', 'CREATED', 'IGNORED', 'REJECTED'], dtype=object)

In [21]:
transf_df.to_csv("data/processed/transformed_dataset_v2.csv",index=False)

In [32]:
transf_df_v2 = pd.get_dummies(transf_df_v2, columns=['booking_status', 'participant_status'], dtype=int)

In [35]:
transf_df_v2 = pd.read_csv("data/processed/transformed_dataset_v2.csv")

In [36]:
transf_df_v2.head()

,compl_count,order_id,trip_distance,driver_id_participant,driver_gps_accuracy,is_completed,driver_distance,event_hour,booking_status_COMPLETED,booking_status_CUSTOMER_CANCELLED,booking_status_DRIVER_CANCELLED,booking_status_DRIVER_FOUND,booking_status_PICKED_UP,participant_status_ACCEPTED,participant_status_CREATED,participant_status_IGNORED,participant_status_REJECTED
0,1,865687867130,1.37,100049799902,68.4,1,0.097266,3,0,0,0,0,1,1,0,0,0
1,1,865687867130,1.37,100049799902,68.4,0,0.097266,3,0,0,0,0,1,0,1,0,0
2,1,865687867130,1.37,100049799902,68.4,1,0.097266,2,0,0,0,1,0,1,0,0,0
3,1,865687867130,1.37,100049799902,68.4,0,0.097266,2,0,0,0,1,0,0,1,0,0
4,1,865687867130,1.37,100049799902,68.4,1,0.097266,3,1,0,0,0,0,1,0,0,0

In [34]:
transf_df_v2.to_csv("data/processed/transformed_dataset_v2.csv",index=False)

join transformed with test to make it compatible with train

In [4]:
test_df = pd.read_csv("data/raw/test_data.csv")

In [10]:
test_df.columns

Index(['event_timestamp', 'order_id', 'customer_id', 'trip_distance',
       'pickup_latitude', 'pickup_longitude', 'driver_id', 'driver_latitude',
       'driver_longitude', 'driver_gps_accuracy'],
      dtype='object')

In [5]:
df = pd.read_csv("data/processed/transformed_dataset.csv")

In [5]:
df.columns

Index(['compl_count', 'order_id', 'trip_distance', 'driver_id_participant',
       'driver_gps_accuracy', 'is_completed', 'driver_distance', 'event_hour',
       'booking_status_COMPLETED', 'booking_status_CUSTOMER_CANCELLED',
       'booking_status_DRIVER_CANCELLED', 'booking_status_DRIVER_FOUND',
       'booking_status_PICKED_UP', 'participant_status_ACCEPTED',
       'participant_status_CREATED', 'participant_status_IGNORED',
       'participant_status_REJECTED'],
      dtype='object')

In [6]:
test_df_v2 = pd.merge(test_df, df, left_on="driver_id", right_on="driver_id_participant", how="inner")

In [8]:
test_df_v2.columns

Index(['event_timestamp', 'order_id_x', 'customer_id', 'trip_distance_x',
       'pickup_latitude', 'pickup_longitude', 'driver_id', 'driver_latitude',
       'driver_longitude', 'driver_gps_accuracy_x', 'compl_count',
       'order_id_y', 'trip_distance_y', 'driver_id_participant',
       'driver_gps_accuracy_y', 'is_completed', 'driver_distance',
       'event_hour', 'booking_status_COMPLETED',
       'booking_status_CUSTOMER_CANCELLED', 'booking_status_DRIVER_CANCELLED',
       'booking_status_DRIVER_FOUND', 'booking_status_PICKED_UP',
       'participant_status_ACCEPTED', 'participant_status_CREATED',
       'participant_status_IGNORED', 'participant_status_REJECTED'],
      dtype='object')

In [ ]:
test_df_v2.drop(columns = ['event_timestamp','order_id_x'])

In [13]:
test_df_v2[['trip_distance_x','trip_distance_y']]

          trip_distance_x  trip_distance_y
0                   2.000            1.189
1                   2.000            1.189
2                   2.000            1.189
3                   2.000            1.189
4                   2.000            1.189
...                   ...              ...
13060194            9.791            3.007
13060195            9.791            3.007
13060196            9.791            3.007
13060197            9.791            3.007
13060198            9.791            3.007

[13060199 rows x 2 columns]

In [10]:
df.shape[0]

1099174

In [11]:
test_df.shape[0]

100000

In [12]:
test_df_v2.shape[0]

13060199